import './js/modal';
import './js/main-page-render';
import './js/make-header.js';
import './js/make-empty-template-my-library';
import './js/button-filter';
import './js/search-movie';
// import './js/modal';
import './js/team-modal';
import './js/local-storage';
import './js/firebase';
import './js/auth-modal';
import './js/pagination';
// import './js/modal';
